// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_error
void test_error();
RcppExport SEXP _testerror_test_error() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_error();
    return R_NilValue;
END_RCPP
}
// test_error2
void test_error2();
RcppExport SEXP _testerror_test_error2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_error2();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testerror_test_error", (DL_FUNC) &_testerror_test_error, 0},
    {"_testerror_test_error2", (DL_FUNC) &_testerror_test_error2, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_testerror(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
