# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_error <- function() {
    invisible(.Call('_testerror_test_error', PACKAGE = 'testerror'))
}

test_error2 <- function() {
    invisible(.Call('_testerror_test_error2', PACKAGE = 'testerror'))
}

